### PR TITLE
Reduce access to global state in functions

### PR DESCRIPTION
**Pull request by seifertm**
This PR substitutes access to constants and global state with function parameters as suggested in #58.
It only touches `lib/new.sh` and there should be no functional changes.
The refactoring is not complete, but since I probably cannot continue to work on this anytime soon, I'd rather file a PR with what I have.

### CODE REVIEW

**Comment by edannenberg** [comment]
Thanks for the effort, unfortunately, and as you have probably already noticed :P, pure functions and bash can be very awkward, specially when assoc. arrays come into play. At some point you have to just embrace some global mutable state if you want to keep some sanity. The variable naming conventions should help with clarity in that regard.

That being said the `new` command was pretty messy and I refactored things a bit further based on your PR, should get merged with the upcoming monthly rebuild.

**Comment by seifertm** [comment]
Sounds good to me! So this PR can simply be closed? (No hard feelings if my changes get lost. They were made while I explored how much effort it would be to make Kubler fit my use case)

As an aside, I do agree to some extent about the awkwardness. On the flip side, functions accessing global variables are pretty much untestable. I think this problem shows that Kubler has outgrown the capabilities of Bash. As I see it, Kubler would benefit greatly from a language that is better suited to application programming. This would allow extracting reusable libraries, simplify testing, and potentially attract more contributors. That doesn't mean Bash has to be abandoned completely, as projects like [dgr](https://www.github.com/blablacar/dgr) show. They do use shell scripts to define the image build process, but rely on Go for dgr's internal application logic and tooling.

**Comment by edannenberg** [comment]
Dropped 6 commits and squashed/merged the rest (thanks for atomic commits btw, pleasure to work with 👍).

The dropped commits were mostly related to replacing the usage of global constants with function args, while I agree with the intention of having pure functions, there are some limitations in Bash that make it not always worthwhile, well at least for me. :) So instead I went the pragmatic way and embraced the situation and consistency, considering the whole project is just a relatively simple short-running (in terms of code paths heh) script it's not too bad. (excluding the old new.sh :P)  Generally I try to avoid global mutation when possible, but personally I think using the constants directly is fine and keeps the code much easier on the eyes.

Anyways, I refactored things a bit further, hopefully much better to work with now, though there is def. still room for improvement. PR as always welcome ;P

> I think this problem shows that Kubler has outgrown the capabilities of Bash.

Fair point, the issue with a language switch is for the most part that currently Kubler pretty much fills all my needs when it comes to image building, and generally speaking I'm fairly happy with the current state and the simplicity Bash brings to the table. So it's kinda hard to justify the required time investment for me. Should I ever decide to learn Go this is probably the project to do it with though. :)

> That doesn't mean Bash has to be abandoned completely, as projects like dgr show. They do use shell scripts to define the image build process, but rely on Go for dgr's internal application logic and tooling.

Yea, Bash for the image build instructions is pretty much required or flexibility suffers. Should also reduce the effort of a switch considerably, hmm maybe next year it's time for the final evolution, we will see.

**Comment by seifertm** [comment]
Great, thanks!

I have no experience with Go whatsoever and don't know if it would be suitable for kubler (I'm more of a Python person). I just wanted to make a point.

However, I do feel with you when you say that it would be a lot of effort (mostly for you, though you probably won't be alone). I already appreciate that you keep supporting kubler and help people out!

**Pull request closed without merging**
