### PR TITLE
Changed use of sed to be compliant with POSIX

### PR DESCRIPTION
**Pull request by neerdoc**
Tested on Mac OS X Catalina (10.15.2).

### CODE REVIEW

**Comment by neerdoc** [comment]
Found a few more places where -i was used without an empty argument. Added commits to PR.

**Comment by edannenberg** [comment]
Thanks! Did a quick test and `-i ''` fails on Linux as it interprets it as empty regex rule and tries to load the following regex as filename. However `-i''` (no space) would work on Linux, would this also work with the Mac version?

```
-i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
```

**Comment by neerdoc** [comment]
Yes, that works on OS X too. Updated PR with a new commit.

**Comment by edannenberg** [comment]
Nice! Built some images from scratch including stage3 update on this PR. Everything seems to be in order.

**Pull request closed without merging**
