### PR TITLE
Added alternative overlay sync function to build-root.sh

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by jbergstroem** [comment]
Wouldn't it be easier to just add the file as part of your own builder?

**Comment by soredake** [comment]
If @edannenberg will say that it is not necessary, so it will be.

**Comment by edannenberg** [comment]
As I said in #93 I think it's a good addition, I want to rebase a few things before I merge this though and didn't have the time yet. Soon(tm).

**Comment by edannenberg** [comment]
@soredake Sorry, not much time lately. I gave this some more thought and the function should be named `add_overlay <id> <url> <mode>`. Maybe with an additional thin wrapper `add_git_overlay <id> <url>` as git is probably the most common overlay type.

**Comment by soredake** [comment]
Ok, i'll edit commit later.

**Comment by edannenberg** [comment]
Refactored and merged manually. Thanks!

**Pull request closed without merging**
