### PR TITLE
add zlib dependency for nodejs

### PR DESCRIPTION
**Pull request by azimut**
node is linked to this library (tested on a musl build)

### CODE REVIEW

**Comment by edannenberg** [comment]
Thanks!

**Comment by jbergstroem** [comment]
@edannenberg perhaps its not for libressl or something?

**Comment by azimut** [comment]
Ouch. Sorry I did disable zlib on my openssl. My bad. You can unmerge (? this.

**Comment by edannenberg** [comment]
No biggie, should only have resulted in a warning as zlib was already in package.provided. Reverted the commit.

**Pull request merged**
