### PR TITLE
Do not merge - Crossdev arm support

### PR DESCRIPTION
**Pull request by azimut**
Hi! Thanks for opensource this project!

This is my current take to add basic armv7 support. I was mainly opening this to ask if there is interest on add arm support on the main repo. If so, I could work on the code to make it fit with everything else instead of replacing current builders. Also I might need to work on build the qemu-arm binary on a container instead of adding it to the repo.

### CODE REVIEW

**Comment by edannenberg** [comment]
Thanks for the PR!

A few questions as I'm not familiar with arm in general:

* I'm assuming the point is to provide docker images for arm devices like raspberry2, do standard ebuilds from the main overlay work well with crossdev-arm?
* What is the function of the qemu-arm binary?

**Comment by azimut** [comment]
> I'm assuming the point is to provide docker images for arm devices like raspberry2
Right that's the idea. Besides the "alpine" images for arm I haven't found anything small and configurable that I could build for ARM.

> do standard ebuilds from the main overlay work well with crossdev-arm?
Actually I realize that what I did was only cross-compile busybox. So now I am creating a new "namespace","builder" and images to try that.

>  What is the function of the qemu-arm binary?
Having that static binary allows the execution of arm ELF files on a x86_64 machine. That's needed here to run the steps that are on the Dockerfile which not run on the builder.

If crossdev doesn't work the other option would be just use a stage3-arm image from gentoo along with the qemu-arm binary. But compiling stuff there might be really slow. Any other idea?

**Comment by edannenberg** [comment]
>> do standard ebuilds from the main overlay work well with crossdev-arm?

> Actually I realize that what I did was only cross-compile busybox. So now I am creating a new "namespace","builder" and images to try that.

As it's all based on glibc it will probably work out fine, if so we could provide a bob-arm7 build container in the gentoo-bb namespace that could be used as default build container via some build.conf configuration. Will probably need some general tweaking though regarding the uclibc busybox build.

>>  What is the function of the qemu-arm binary?

> Having that static binary allows the execution of arm ELF files on a x86_64 machine. That's needed here to run the steps that are on the Dockerfile which not run on the builder.

Ah, I see. Thanks for the clarification.

> If crossdev doesn't work the other option would be just use a stage3-arm image from gentoo along with the qemu-arm binary. But compiling stuff there might be really slow. Any other idea?

Yea from what I heard qemu-arm compiling is not really feasable. Not really an alternative, but it might be nice to have a crossdev-arm distcc image you could easily deploy on build slaves. Might actually be a good feature for all build containers. Hmm, I will give that some more thought. :)

Let me know if you need help with anything.

**Comment by azimut** [comment]
A distcc "swarm" sounds awesome (especially for my actual x86_64 boxes) will look around for that.

I am working on the new builder here https://github.com/azimut/gentoo-bb/tree/newarmbuilder

I just hit an infinite loop when I changed the default builder on dock/gentoobb/build.conf to my new builder. That is happening on build.sh:check_builder_dependencies I just hardcoded my builder along the core builder to stop the infinite loop. Not sure how to fix it properly for now.

**Comment by azimut** [comment]
More importantly now I am hitting this while compiling s6. While that file is not in that exact directory on gentoobb/bob-armv7a-glibc:20151231 it's on the /usr/arm.../lib/ directory. Might be I am missing to unset a flag?

```
Calculating dependencies... done!
[ebuild  N     ] dev-libs/skalibs-2.3.2.0::gentoo to /emerge-root/ USE="-doc -ipv6 -static-libs" 0 KiB
[ebuild  N     ] dev-lang/execline-2.1.1.0::gentoo to /emerge-root/ USE="-static -static-libs" 75 KiB
[ebuild  N     ] sys-apps/s6-2.1.3.0::gentoo to /emerge-root/ USE="-static" 177 KiB

Total: 3 packages (3 new), Size of downloads: 252 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 3) dev-libs/skalibs-2.3.2.0::gentoo for /emerge-root/
 * skalibs-2.3.2.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                  [ ok ]
>>> Unpacking source...
>>> Unpacking skalibs-2.3.2.0.tar.gz to /usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work
>>> Source unpacked in /usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work
>>> Preparing source in /usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work/skalibs-2.3.2.0 ...
>>> Source prepared.
>>> Configuring source in /usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work/skalibs-2.3.2.0 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=armv7a-hardfloat-linux-gnueabi --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-ipv6 --disable-static --dynlibdir=/lib --libdir=/usr/lib/skalibs --datadir=/etc --sysdepdir=/usr/lib/skalibs --enable-force-devr
Checking for C compiler...
  ... armv7a-hardfloat-linux-gnueabi-gcc
Checking whether C compiler works... 
  ... yes
Checking target system type...
  ... armv7a-hardfloat-linux-gnueabi
Checking whether compiler accepts -std=c99 ...
  ... yes
Checking whether compiler accepts -fomit-frame-pointer ...
  ... yes
Checking whether compiler accepts -fno-exceptions ...
  ... yes
Checking whether compiler accepts -fno-unwind-tables ...
  ... yes
Checking whether compiler accepts -fno-asynchronous-unwind-tables ...
  ... yes
Checking whether compiler accepts -Wa,--noexecstack ...
  ... yes
Checking whether compiler accepts -fno-stack-protector ...
  ... yes
Checking whether compiler accepts -Werror=implicit-function-declaration ...
  ... yes
Checking whether compiler accepts -Werror=implicit-int ...
  ... yes
Checking whether compiler accepts -Werror=pointer-sign ...
  ... yes
Checking whether compiler accepts -Werror=pointer-arith ...
  ... yes
Checking whether socket functions need an additional library...
  ... no
Checking whether clock functions are available...
  ... yes
Checking whether system has CLOCK_MONOTONIC...
  ... yes
Checking system endianness...
/lib/ld-linux-armhf.so.3: No such file or directory
./configure: unable to determine endianness
 * ERROR: dev-libs/skalibs-2.3.2.0::gentoo failed (configure phase):
 *   econf failed
 * 
 * Call stack:
 *               ebuild.sh, line  90:  Called src_configure
 *             environment, line 687:  Called econf '--disable-ipv6' '--disable-static' '--dynlibdir=/lib' '--libdir=/usr/lib/skalibs' '--datadir=/etc' '--sysdepdir=/usr/lib/skalibs' '--enable-force-devr'
 *        phase-helpers.sh, line 662:  Called __helpers_die 'econf failed'
 *   isolated-functions.sh, line 117:  Called die
 * The specific snippet of code:
 *              die "$@"
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/skalibs-2.3.2.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/skalibs-2.3.2.0::gentoo'`.
 * The complete build log is located at '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/temp/build.log'.
 * The ebuild environment file is located at '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/temp/environment'.
 * Working directory: '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work/skalibs-2.3.2.0'
 * S: '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work/skalibs-2.3.2.0'
```

**Comment by edannenberg** [comment]
Hard to tell, might also be a bug with the s6 packages/source. If you haven't already try with a interactive build first:

    ./bin/bob-interactive.sh gentoobb/s6

Will probably take a few days before I get the time to play around with your branch.

**Comment by edannenberg** [comment]
Sorry for the delay. I'll have a closer look at your branch the next couple days. 
 
> Might be I am missing to unset a flag?

Or maybe one too many? :p It's looking in the wrong place so it's probably gonna be something along those lines, unless s6 itself is a bit borked when it comes to cross compiling. Best way to find out is debugging with the interactive build.

**Comment by azimut** [comment]
Sorry too, I got sidetracked with some other stuff. Will look at this at the weekend :D

**Comment by edannenberg** [comment]
Finally managed to take a good look at this and fixed some bugs along the way. `Skalibs` builds fine now with the vanilla s6 Buildconfig.sh, but `Execline` fails with:

```    
checking target system type...
  ... armv7a-hardfloat-linux-gnueabi
./configure: error: target armv7a-hardfloat-linux-gnueabi does not match the contents of /usr/lib64/skalibs/target
```

Also had to remove `-march` from `CFLAGS` beforehand, as it would not recognize any arm related values.

Looks like some issues in the s6 build to me, probably should file a bug upstream. Would not be surprised if you are the first one to cross build s6 for arm, it's a fairly young project with a small user base.

I'll need to test a few more things before I push the general fixes to master, hopefully done by the weekend.

**Comment by edannenberg** [comment]
Crossdev support should be much better now, see 4f292760bfe337dba47915273ed860a2134da9e9 for example armv7a setup. The qemu-arm binary handling is missing though.

All other errors should be issues with the respective sources and/or ebuilds.

I hit almost the exact same issue as you now regarding s6:

```
Checking whether system has CLOCK_MONOTONIC...
  ... yes
Checking system endianness...
./configure: line 434: ./tryendianness: cannot execute binary file: Exec format error
./configure: unable to determine endianness
```

The build is trying to run to a small helper it compiled for arm.

```
$ find . -name tryendianness*
./usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work/skalibs-2.3.2.0/src/sysdeps/tryendianness.c
./usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-libs/skalibs-2.3.2.0/work/skalibs-2.3.2.0/tryendianness
```

So yeah, clearly some problem with the s6 sources not being ready for crossbuilding non x86 targets.
You can probably live fine without s6 unless you need to run multiple processes per container.

**Comment by skarnet** [comment]
skalibs cross-configuration is tricky and it appears that gentoo is not doing it properly. Please check http://skarnet.org/software/skalibs/crosscompile.html for more information.

 The gist of it is that _you need sysdeps files for your target architecture_, here `armv7a-hardfloat-linux-gnueabi`. You can obtain such sysdeps by natively running the `./configure` step of skalibs inside a qemu-system-arm, or by crafting them by hand.

Once you have the sysdeps, skalibs (and execline and s6) will build easily.

**Comment by soredake** [comment]
if @azimut is alive, you can help me here https://github.com/edannenberg/gentoo-bb/issues/39

**Comment by edannenberg** [comment]
I think the information in this PR is outdated to a point it is confusing for others now. Closing.

**Pull request closed without merging**
